<?php

/**
 * @file
 * Primary module hooks for Pokemon API Sync module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_help().
 */
function pokemon_api_sync_help(string $route_name, RouteMatchInterface $route_match): string {
  if ($route_name == 'help.page.pokemon_api_sync') {
    $output = 'Help Page';
    return $output;
  }

  return '';
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function pokemon_api_sync_entity_bundle_field_info_alter(array &$fields, EntityTypeInterface $entity_type, $bundle) {
  // Add a validation callback to the content type form.
  if ($entity_type->id() === 'node' && $bundle === 'pokemon') {
    foreach ($fields as $field_name => $field_info) {
      if ($field_info->getType() === 'entity_reference_revisions' && $field_info->getSetting('target_type') === 'paragraph') {
        $fields[$field_name]->addConstraint('StatParagraphLimit');
      }
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function pokemon_api_sync_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'entity_bundle_field_info_alter') {
    $implementations['pokemon_api_sync'] = -100;
  }
}