# Schema for the configuration files of the Pokemon API module.
pokemon_api.settings:
  type: config_object
  label: 'Pokemon API settings'
  mapping:
    base_url:
      type: url
      label: 'Poke API Url'
